// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFile(name: string): $CancellablePromise<$models.CurlFile> {
    return $Call.ByID(3418645411, name);
}

export function DeleteFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2962294020, path);
}

export function GetRunSnapshot(runID: string): $CancellablePromise<$models.RunSnapshot> {
    return $Call.ByID(395348492, runID);
}

export function ListEnvironments(): $CancellablePromise<$models.Environment[] | null> {
    return $Call.ByID(3495340119);
}

export function ListFiles(): $CancellablePromise<$models.CurlFile[] | null> {
    return $Call.ByID(3557170708);
}

export function OpenGitHub(): $CancellablePromise<void> {
    return $Call.ByID(4026132870);
}

export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1160596971, path);
}

export function RunCurl(command: string, environment: string): $CancellablePromise<string> {
    return $Call.ByID(2250733076, command, environment);
}

export function SaveFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1396636678, path, content);
}

export function StopCurl(runID: string): $CancellablePromise<void> {
    return $Call.ByID(3144992195, runID);
}
