// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";
import * as $models from "./models.js";

export function GetDiagnostics(): $CancellablePromise<$models.DiagnosticInfo> { return $Call.ByID(2426292737); }
export function RunCurl(command: string): $CancellablePromise<$models.RunResult> { return $Call.ByID(2359614728, command); }
export function RunCurlStream(command: string, runID: string): $CancellablePromise<$models.RunResult> { return $Call.ByID(3716915640, command, runID); }
export function SetCurlPath(path: string): $CancellablePromise<void> { return $Call.ByID(1431115278, path); }
export function SetTimeout(timeoutMs: number): $CancellablePromise<void> { return $Call.ByID(898821362, timeoutMs); }
export function StopCurl(): $CancellablePromise<void> { return $Call.ByID(2867331999); }
export function StopCurlByID(runID: string): $CancellablePromise<void> { return $Call.ByID(4145819831, runID); }
export function ValidateCurl(command: string): $CancellablePromise<$models.CurlValidation> { return $Call.ByID(4111860629, command); }
