// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface WorkspaceEntry {
    "path": string;
    "name": string;
    "folder": string;
    "isDir": boolean;
    "size": number;
}

export interface RunResult {
    "output": string;
    "exitCode": number;
}
