// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface WorkspaceEntry {
    "path": string;
    "name": string;
    "folder": string;
    "isDir": boolean;
    "size": number;
}

export interface WorkspaceInfo {
    "path": string;
    "name": string;
}

export interface RunResult {
    "output": string;
    "exitCode": number;
    "status": number;
    "durationMs": number;
    "requestSize": number;
    "responseSize": number;
    "responseHeaders": string;
}

export interface CurlDiagnostic {
    "line": number;
    "column": number;
    "message": string;
    "severity": string;
}

export interface CurlValidation {
    "valid": boolean;
    "diagnostics": CurlDiagnostic[] | null;
}

export interface HistoryEntry {
    "id": string;
    "createdAt": string;
    "filePath": string;
    "environment": string;
    "command": string;
    "output": string;
    "responseHeaders": string;
    "exitCode": number;
    "status": number;
    "durationMs": number;
}

export interface DiagnosticInfo {
    "os": string;
    "architecture": string;
    "curlPath": string;
    "curlVersion": string;
}

export interface WorkspaceSearchResult {
    "path": string;
    "name": string;
    "line": number;
    "snippet": string;
}
