// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";
import * as $models from "./models.js";
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> { return $Call.ByID(3422202730); }
export function InstallUpdate(downloadURL: string): $CancellablePromise<void> { return $Call.ByID(2117874871, downloadURL); }
