// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFile(folder: string, name: string): $CancellablePromise<$models.WorkspaceEntry> {
    return $Call.ByID(3787448474, folder, name);
}

export function CreateFolder(parent: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(585698680, parent, name);
}

export function DeleteEntry(relative: string): $CancellablePromise<void> {
    return $Call.ByID(2468227501, relative);
}

export function ListWorkspace(): $CancellablePromise<$models.WorkspaceEntry[] | null> {
    return $Call.ByID(1335838253);
}

export function ReadFile(relative: string): $CancellablePromise<string> {
    return $Call.ByID(2517090602, relative);
}

export function RenameEntry(relative: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2590253538, relative, name);
}

export function SaveFile(relative: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3758940195, relative, content);
}
