// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFile(folder: string, name: string): $CancellablePromise<$models.WorkspaceEntry> {
    return $Call.ByID(3787448474, folder, name);
}

export function CreateFolder(parent: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(585698680, parent, name);
}

export function DeleteEntry(relative: string): $CancellablePromise<void> {
    return $Call.ByID(2468227501, relative);
}

export function ListWorkspace(): $CancellablePromise<$models.WorkspaceEntry[] | null> {
    return $Call.ByID(1335838253);
}

export function ListEnvironments(): $CancellablePromise<Record<string, Record<string, string>>> {
    return $Call.ByName("main.WorkspaceService.ListEnvironments");
}

export function LoadSettings(): $CancellablePromise<Record<string, string>> {
    return $Call.ByName("main.WorkspaceService.LoadSettings");
}

export function ReadFile(relative: string): $CancellablePromise<string> {
    return $Call.ByID(2517090602, relative);
}

export function RenameEntry(relative: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2590253538, relative, name);
}

export function SaveFile(relative: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3758940195, relative, content);
}

export function SaveEnvironments(environments: Record<string, Record<string, string>>): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.SaveEnvironments", environments);
}

export function SaveSettings(settings: Record<string, string>): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.SaveSettings", settings);
}

export function ResolveEnvironment(command: string, environment: string): $CancellablePromise<string> {
    return $Call.ByName("main.WorkspaceService.ResolveEnvironment", command, environment);
}

export function ValidateEnvironment(command: string, environment: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("main.WorkspaceService.ValidateEnvironment", command, environment);
}

export function LoadDotEnv(): $CancellablePromise<Record<string, string>> {
    return $Call.ByName("main.WorkspaceService.LoadDotEnv");
}

export function SaveDotEnv(values: Record<string, string>): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.SaveDotEnv", values);
}

export function RecordHistory(filePath: string, environment: string, command: string, output: string, responseHeaders: string, exitCode: number, status: number, durationMs: number): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.RecordHistory", filePath, environment, command, output, responseHeaders, exitCode, status, durationMs);
}

export function ListHistory(query: string): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByName("main.WorkspaceService.ListHistory", query);
}

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.ClearHistory");
}

export function SearchWorkspace(query: string): $CancellablePromise<$models.WorkspaceSearchResult[] | null> {
    return $Call.ByName("main.WorkspaceService.SearchWorkspace", query);
}

export function CurrentWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByName("main.WorkspaceService.CurrentWorkspace");
}

export function ListRecentWorkspaces(): $CancellablePromise<$models.WorkspaceInfo[] | null> {
    return $Call.ByName("main.WorkspaceService.ListRecentWorkspaces");
}

export function CreateWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByName("main.WorkspaceService.CreateWorkspace", path);
}

export function OpenWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByName("main.WorkspaceService.OpenWorkspace", path);
}

export function ImportWorkspace(path: string): $CancellablePromise<void> {
    return $Call.ByName("main.WorkspaceService.ImportWorkspace", path);
}
